### ISSUE TITLE
python 3.12 import fails

### ISSUE THREAD

**Issue by pichwo** [dwt/fluent#14]
=============================================================
(python environment governed via pyenv : here : use globally installed 3.12

$ pip show fluentpy
Name: fluentpy
Version: 2.1.1
Summary: Python wrapper for stdlib (and your) objects to give them a fluent interface.
Home-page: https://github.com/dwt/fluent
Author: Martin Häcker
Author-email: mhaecker@mac.com
License: ISC
Location: /usr/local/lib/python3.12/site-packages
Requires: 
Required-by: 

$ python
Python 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fluentpy as _
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/fluentpy/__init__.py", line 36, in <module>
    import fluentpy.wrapper
  File "/usr/local/lib/python3.12/site-packages/fluentpy/wrapper.py", line 112, in <module>
    class Wrapper(object):
  File "/usr/local/lib/python3.12/site-packages/fluentpy/wrapper.py", line 303, in Wrapper
    type = wrapped(type)
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fluentpy/wrapper.py", line 71, in wrapped
    @functools.wraps(wrapped_function)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/functools.py", line 56, in update_wrapper
    setattr(wrapper, attr, value)
TypeError: __type_params__ must be set to a tuple
>>> 

=============================================================
(python environment governed via pyenv : here : use locally installed 3.11)

$ pip show fluentpy
Name: fluentpy
Version: 2.1.1
Summary: Python wrapper for stdlib (and your) objects to give them a fluent interface.
Home-page: https://github.com/dwt/fluent
Author: Martin Häcker
Author-email: mhaecker@mac.com
License: ISC
Location: /home/rotten/.pyenv/versions/3.11.3/lib/python3.11/site-packages
Requires: 
Required-by: 

$ python
Python 3.11.3 (main, Apr 30 2024, 19:38:50) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fluentpy as _
>>> 

=============================================================
what to do ?
in need of any further information ?

thx
w.

**Comment by dwt** [comment]
Oh my, that is indeed reproducible. Thanks a lot for the report.

From first look, it seems that I'm using `functools.wraps()` incorrectly, but I don't get it yet, as it seems that I'm doing the basic thing of just handing in a simple function. ¿¿¿

I'll have to look into that more deeply.

**Comment by dwt** [comment]
Looks like this is a cpython issue and needs to be fixed there. Feel free to also monitor their bug!

**Comment by javadba** [comment]
is this fixed whether in cpython or elsewhere?

**Comment by dwt** [comment]
I have to admit that I didn't really follow this bug. The Upstream bug was fixed in 3.12.4, so I would imagine yes. Can you still reproduce it? If so please reopen.

What I can confirm is that python 3.9, 3.11, 3.12, 3.13 and 3.14 work fine.
